# -*- coding: utf-8 -*-
"""prodigy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhJM9uaQoQCzrBdvEwZ2X2plAXcp6z7F
"""

import pandas as pd

df=pd.read_csv("/content/ds1.csv")

df.columns

df.drop(columns=['Indicator Name','Indicator Code','Country Name'],inplace=True)

df.head()

import matplotlib.pyplot as plt

import numpy as np

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

df.plot(figsize=(10,6))
plt.xlabel("Year")
plt.ylabel("Total Population")
plt.title("Total Population by Year")
plt.show()

"""task 2"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/content/train.csv')

data.head(5)

data.head(5)

data.info()

data.describe(include='all')

data=data.drop(['Name'],axis=1)

data['Age']=data.Age.fillna(data['Age'].median())
data['Cabin']=data.Cabin.fillna('B96')
data['Embarked']=data.Embarked.fillna('S')

for i in data.select_dtypes(include='float').columns:
  data[i] = data[i].astype(int)

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(data['Sex'])
data['Sex']=le.transform(data['Sex'])

data.info()

data.head(10)

data.describe(include='all')

import seaborn as sns

plt.figure(figsize=(15,18))
sns.heatmap(data.drop(['SibSp','Parch','Embarked'],axis=1).corr(),annot=True,vmin=-1,vmax=1)
plt.show()

sns.barplot(x='Pclass', y='Survived', data=data)
plt.show()

plt.figure(figsize=(15,15))
sns.barplot(x='Cabin',y='Survived',data=data)
plt.show()

plt.figure(figsize=(15,15))
sns.barplot(x='Age',y='Survived',data=data)
plt.show()

sns.barplot(x='Sex', y='Survived', data=data, hue='Sex', ci=None, order=[1,0])
plt.legend(labels=['Male','Female'])
plt.show()